### ISSUE TITLE
Yarn or npm?

### ISSUE THREAD

**Issue by connerbw** [pressbooks/local-development#4]
MacOS document mentions [yarn](https://yarnpkg.com/lang/en/). Pressbooks code has a [yarn.lock](https://github.com/pressbooks/pressbooks/blob/dev/yarn.lock)

However, our Contributing guide says to use [npm](https://github.com/pressbooks/pressbooks/blob/dev/.github/CONTRIBUTING.md#installing-for-development).

Is yarn mandatory?

**Comment by greatislander** [comment]
Haven't got around to updating the contributing guide, but Yarn is much faster and it generates a lock file which will guarantee that someone installing dependencies will get exactly what they are supposed to get.

**Comment by greatislander** [comment]
(So: my vote is strongly for yarn and I need to update my docs.)

**Comment by connerbw** [comment]
Ok thanks. I'll update the Windows instructions to use yarn as well.
